### ISSUE TITLE
Must disable light ID tracking under scene mode

### ISSUE THREAD

**Issue by tkuro11** [tkuro11/helvar_server#4]
- [x]  states情報に scene_flag 追加。default  = false
- [x] scene_no != 0 で scene_flag = true
- [ ] XML受信ルーチンは scene_flag == true の場合、direct levelをいじらない

``` javascript:index.js
        if (!states.scene_flag) { directlevel.rgb(....); }
```
- [ ] scene_no == 0 の時は scene_flag = false  。その後、全 default_colorに設定, 端末IDスキャンで色かえ。衝突は考慮しない。
